[workspace]
members = ["monobase", "monocore", "monofs", "monovue"]
resolver = "2"

[workspace.package]
license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"
tokio = { version = "1.34", features = ["full"] }
dotenvy = "0.15"
reqwest = { version = "0.12", features = ["json"] }
tracing = "0.1.40"
tracing-subscriber = "0.3"
clap = { version = "4.5.16", features = ["color", "derive"] }
getset = "0.1.3"
