[package]
name = "monobase"
version = "0.1.0"
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "monobase"
path = "lib/lib.rs"

[dependencies]
