[package]
name = "monocore"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
name = "monocore"
path = "lib/lib.rs"

[[bin]]
name = "monocore"
path = "bin/monocore.rs"

[dependencies]
anyhow.workspace = true
async-trait = "0.1.83"
axum = "0.7.7"
bytes = "1.7.2"
chrono = { version = "0.4.38", features = ["serde"] }
clap.workspace = true
dirs = "5.0.1"
dotenvy.workspace = true
futures.workspace = true
getset.workspace = true
hex = "0.4.3"
lazy_static = "1.5.0"
oci-spec = "0.7.0"
reqwest = { workspace = true, features = ["stream"] }
reqwest-middleware = "0.3.3"
reqwest-retry = "0.6.1"
serde.workspace = true
serde_json = "1.0.128"
sha2 = "0.10.8"
structstruck = "0.4.1"
thiserror.workspace = true
tokio.workspace = true
toml = "0.8.19"
tracing.workspace = true
tracing-subscriber.workspace = true
typed-builder = "0.20.0"
typed-path = "0.9.2"
xattr = "1.3.1"

[dev-dependencies]
test-log = "0.2.16"
